{
  "comments": [
    {
      "key": {
        "uuid": "1a76adc5_1524fe0a",
        "filename": "osdf/optimizers/pciopt/pci_opt_processor.py",
        "patchSetId": 3
      },
      "lineNbr": 76,
      "author": {
        "id": 3455
      },
      "writtenOn": "2018-09-20T01:03:43Z",
      "side": 1,
      "message": "for better readability, I would advise to first build solutions dict and then populate pci_response with the required fields altogether.",
      "revId": "d00c64e8637a0d39788e38ce2de9e94258ca6b24",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a76adc5_550ef68c",
        "filename": "osdf/optimizers/pciopt/pci_opt_processor.py",
        "patchSetId": 3
      },
      "lineNbr": 82,
      "author": {
        "id": 3455
      },
      "writtenOn": "2018-09-20T01:03:43Z",
      "side": 1,
      "message": "Would you prefer to remove the commented line?",
      "revId": "d00c64e8637a0d39788e38ce2de9e94258ca6b24",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a76adc5_f52862e3",
        "filename": "osdf/optimizers/pciopt/pci_opt_processor.py",
        "patchSetId": 3
      },
      "lineNbr": 91,
      "author": {
        "id": 3455
      },
      "writtenOn": "2018-09-20T01:03:43Z",
      "side": 1,
      "message": "may I know why it is logged as error?",
      "revId": "d00c64e8637a0d39788e38ce2de9e94258ca6b24",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    }
  ]
}